server:
  port: 8031

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yami_shops?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com.person.gen.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  row-bounds-with-count: true

gen:
  author: fu.yuanming
  packageName: com.person.gen